// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmJ5RBxdq2WJvnHWkBwTDeeb1qvxVPKkI',
    appId: '1:110749291342:web:eb0db2de78e9188be9441f',
    messagingSenderId: '110749291342',
    projectId: 'rooflix-app',
    authDomain: 'rooflix-app.firebaseapp.com',
    databaseURL: 'https://rooflix-app-default-rtdb.firebaseio.com',
    storageBucket: 'rooflix-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3eo55U9kgJA3m_XIEMmMJfGLK4TXnLRw',
    appId: '1:110749291342:android:269d9fb1bca8e994e9441f',
    messagingSenderId: '110749291342',
    projectId: 'rooflix-app',
    databaseURL: 'https://rooflix-app-default-rtdb.firebaseio.com',
    storageBucket: 'rooflix-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg5RunwXx2IN7jTqSp27LEwvHTS1uNEzc',
    appId: '1:110749291342:ios:0d195c9b47b768dde9441f',
    messagingSenderId: '110749291342',
    projectId: 'rooflix-app',
    databaseURL: 'https://rooflix-app-default-rtdb.firebaseio.com',
    storageBucket: 'rooflix-app.firebasestorage.app',
    iosClientId: '110749291342-6m68kpchhbsu8iso436see4hl1eu6b9g.apps.googleusercontent.com',
    iosBundleId: 'com.questrax.rooflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg5RunwXx2IN7jTqSp27LEwvHTS1uNEzc',
    appId: '1:110749291342:ios:0d195c9b47b768dde9441f',
    messagingSenderId: '110749291342',
    projectId: 'rooflix-app',
    databaseURL: 'https://rooflix-app-default-rtdb.firebaseio.com',
    storageBucket: 'rooflix-app.firebasestorage.app',
    iosClientId: '110749291342-6m68kpchhbsu8iso436see4hl1eu6b9g.apps.googleusercontent.com',
    iosBundleId: 'com.questrax.rooflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmJ5RBxdq2WJvnHWkBwTDeeb1qvxVPKkI',
    appId: '1:110749291342:web:d455457ec7bb1d8de9441f',
    messagingSenderId: '110749291342',
    projectId: 'rooflix-app',
    authDomain: 'rooflix-app.firebaseapp.com',
    databaseURL: 'https://rooflix-app-default-rtdb.firebaseio.com',
    storageBucket: 'rooflix-app.firebasestorage.app',
  );
}
